Dev
bezrukovq/NumFac pull request #12
Opened 2019-03-03 14:40 UTC by bezrukovq

Moxy
DB
Dialog
New FavList

2019-03-04 22:42 UTC, NailShaykhrazievItis requested changes

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/model/DB/DateRepository.kt
> +class DateRepository(val dateDAO: DateDAO?) {
Думаю тут нет особо смысла в ?
оно только проблемы создает

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/presenter/FavListPresenter.kt
> +            onError = {})
думаю тут перенос строки был лишен

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/dialogs/DownloadSizeDialog.kt
> +        targetFragment?.onActivityResult(
запускать другой экран через фрагмент такое себе, это не его зона ответственности, пусть это делает его родитель

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateDetailsFragment.kt
> +    private var liked = false
isLiked

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateDetailsFragment.kt
> +                showCached(arguments?.getString(ARG_TEXT).toString())
все через презентер. Слишком умная вью. Единственные методы, которые умеет запускать вью сама это иницилизация чего, прокидывайте все эти действия через вью

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateDetailsFragment.kt
> +            like()
презентер

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateDetailsFragment.kt
> +    private fun like() {
override fun

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateDetailsFragment.kt
> +        dateDetailPresenter.saveToFav(DateDB(tv_fact.text as String))
А это уже сразу лежит в презентере. Оверрайднутые методы делают что то со вью и все, не запускают цепь событий еще. и isLiked как стейт вьюшки будет лежать в презентере

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateView.kt
> +@StateStrategyType(value = AddToEndStrategy::class)
AddToEndSingleStrategy на все думаю

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/DateView.kt
>      fun showError(string: String)
Для ошибки oneexecute

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/dateList/DateListView.kt
> +    @StateStrategyType(value = SkipStrategy::class)
OneExecute скорее

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/dateList/DateListView.kt
> +@StateStrategyType(value = AddToEndStrategy::class)
тут тоже

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/dateList/RecyclerAdapter.kt
> +        for (value in values) {
хммм, можно было и листадаптером сделать, ну да ладно

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/dateList/RecyclerFragment.kt
> +    private var recyclerAdapter = RecyclerAdapter { onItemClick(it) }
тут можно было и не оборачивать в метод, но тут вкусовщина, но адаптер я все ж создавал бы в onCreate

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/dateList/RecyclerFragment.kt
> +            val dlg1 = DownloadSizeDialog()
прокидывать через презентер
отдельный метод во вью openDownloandSizeDialog с oneexecutestrategy

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/numfac/view/fragments/favList/FavViewHolder.kt
> +class FavViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
не вижу имплементацию от LayoutContainer

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_dialog.xml
> +        </Button>
Че т у вас xml весь слетел куда то, чекните конфиги в ide

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_dialog.xml
> +                android:id="@+id/btnMinus"
ооуоуо, что за id
btn_minus or button_minus
чекните все id во всех xml
откройте пару по чекстайлу, тут прям косяк

2019-03-04 22:42 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_number_details.xml
> +        android:visibility="gone"
порядок не по алфавиту. ctrl+alt+L
переревьювте весь xml - в каком то ужасном состоянии тут все

2019-03-05 20:18 UTC, bezrukovq commented on app/src/main/java/com/example/numfac/view/fragments/favList/FavViewHolder.kt
> +class FavViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
не понел

2019-03-05 21:08 UTC, NailShaykhrazievItis approved these changes

2019-03-06 08:18 UTC, merged